### ISSUE TITLE
🐛[BUG]: occasional error downloading pangu

### ISSUE THREAD

**Issue by nbren12** [NVIDIA/earth2mip#93]
### Version

main

### Describe the issue

I get this error sometimes
```
INFO:/root/earth2mip/earth2mip/model_registry.py:Downloading Pangu 6hr / 24hr model checkpoints, this may take a bit
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/earth2mip/earth2mip/inference_medium_range.py", line 301, in <module>
    main()
  File "/root/earth2mip/earth2mip/inference_medium_range.py", line 279, in main
    model = _cli_utils.model_from_args(args, dist.device)
  File "/root/earth2mip/earth2mip/_cli_utils.py", line 41, in model_from_args
    return networks.get_model(args.model, device=device, metadata=metadata)
  File "/root/earth2mip/earth2mip/networks/__init__.py", line 337, in get_model
    package = registry.get_model(model)
  File "/root/earth2mip/earth2mip/model_registry.py", line 222, in get_model
    return self.get_builtin_model(name)
  File "/root/earth2mip/earth2mip/model_registry.py", line 237, in get_builtin_model
    return PanguPackage(self.get_path(name), seperator=self.SEPERATOR)
  File "/root/earth2mip/earth2mip/model_registry.py", line 186, in PanguPackage
    urllib.request.urlretrieve(
  File "/usr/lib/python3.10/urllib/request.py", line 280, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 38451195 out of 1181711187 bytes>
```

**Comment by nbren12** [comment]
I wonder if it is possible to get these from https://github.com/198808xc/Pangu-Weather#downloading-trained-models instead of ECWMF (at least when in the US).

**Comment by m13uz** [comment]
Experienced the same issue...
